merge_merged_unfiltered.all.tab :
	wrapParadigm.py -y -p small_pid_66 genome rankAllFile:data/small_pid_66_genome.tab mRNA rankAllFile:data/small_pid_66_mRNA.tab

clean :
	rm -rf merge* clusterFiles pathway dogma config* jobs* outputFiles* params* *.dogma *.imap small_pid_66_*.tab *.err .jobTree .lastjobTree
