merge_merged_unfiltered.all.tab :
	galaxyParadigm.py -y -p small_pid_66 -d ../dogmas/standard genome rankAllFile:data/small_pid_66_genome.tab mRNA rankAllFile:data/small_pid_66_mRNA.tab

clean :
	rm -rf merge* paradigm.ipls clusterFiles pathway dogma config* jobs* outputFiles* params* *.dogma *.imap small_pid_66_*.tab *.log .jobTree .lastTree
