merge_merged_unfiltered.all.tab :
	galaxyParadigm.py -y -p ../pathways/global_v1/ genome rankAllFile:data/Genome_Wide_SNP_6.genome.shared.tab mRNA rankAllFile:data/AgilentG4502A_07.mRNA.shared.tab

clean :
	rm -rf merge* paradigm.ipls clusterFiles pathway dogma config* jobs* outputFiles* params* *.dogma *.imap Genome_Wide_SNP_6.genome.shared.tab AgilentG4502A_07.mRNA.shared.tab *.log .jobTree .lastTree
